# Generated by Django 2.2.6 on 2019-11-06 22:27

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191030_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tag',
            field=models.CharField(max_length=1, validators=[game.models.validate_unique_tag, game.models.validate_player_count]),
        ),
    ]
